
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fgcustom
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fgcustom
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-095f553c680478063::fsap-022a3d01d518fcdee
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
  namespace: prathapfg
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: fgcustom
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: prathapfg
spec:
  containers:
  - name: app1 
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out1.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-claim


apiVersion: v1
kind: Pod
metadata:
  name: app1
  namespace: prathapfg
spec:
  containers:
  - name: app1
    image: codingpuss/postgres-client
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out1.txt; sleep 5; done"]